version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: mijenkins
    ports:
      - 80:8080
      - 50000:50000
    restart: on-failure
    user: root
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

